version: '3.3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  fh-sproof-api-client:
    container_name: fh-sproof-api-client
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
#   command: sh ./scripts/start.sh
    command: sh ./scripts/buildUIAndStart.sh
    volumes:
      - ./data:/usr/src/sproof-api-client/data
      - ./src:/usr/src/sproof-api-client/src
      - ./logs:/usr/src/sproof-api-client/logs
      - ./dist:/usr/src/sproof-api-client/dist
      - ./scripts:/usr/src/sproof-api-client/scripts

    labels:
      - traefik.backend=fh-sproof-api-client
      - traefik.frontend.rule=Host:fhsalzburg.sproof.io
      - traefik.docker.network=web
      - traefik.port=6001

    networks:
      - web
